### ISSUE TITLE
TypeError: res.status is not a function (lib/app.js:180:7)

### ISSUE THREAD

**Issue by fskale** [access-watch/access-watch#126]
Hi,
found your project, which sound very interesting though.
Unfortunately it simply doesn't work.
Error when accessing the interface using a browser:

```
TypeError: res.status is not a function
    at app.use (/opt/access-watch/lib/app.js:180:7)
    at Layer.handle [as handle_request] (/opt/access-watch/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/access-watch/node_modules/express/lib/router/index.js:317:13)
    at /opt/access-watch/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/opt/access-watch/node_modules/express/lib/router/index.js:335:12)
    at next (/opt/access-watch/node_modules/express/lib/router/index.js:275:10)
    at app.use (/opt/access-watch/lib/app.js:26:3)
    at Layer.handle [as handle_request] (/opt/access-watch/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/access-watch/node_modules/express/lib/router/index.js:317:13)
    at /opt/access-watch/node_modules/express/lib/router/index.js:284:7
```
I followed the instruction on your website.

Attached the versions as well as the npm module list.

Best regards
Franz

npm --version
**1.4.21**

node -v
**v8.9.3**

```
npm list:
access-watch@0.7.0 /opt/access-watch
├─┬ access-watch-sdk@0.1.4
│ └─┬ ip-address@5.8.9
│   ├── jsbn@1.1.0
│   ├── lodash.find@4.6.0
│   ├── lodash.max@4.0.1
│   ├── lodash.merge@4.6.0
│   ├── lodash.padstart@4.6.1
│   ├── lodash.repeat@4.1.0
│   └── sprintf-js@1.1.0
├── access-watch-ui@1.3.3
├─┬ ajv@5.5.2
│ ├── co@4.6.0
│ ├── fast-deep-equal@1.0.0
│ ├── fast-json-stable-stringify@2.0.0
│ └── json-schema-traverse@0.3.1
├─┬ axios@0.17.1
│ ├─┬ follow-redirects@1.3.0
│ │ └─┬ debug@3.1.0
│ │   └── ms@2.0.0
│ └── is-buffer@1.1.6
├─┬ body-parser@1.18.2
│ ├── bytes@3.0.0
│ ├── content-type@1.0.4
│ ├─┬ debug@2.6.9
│ │ └── ms@2.0.0
│ ├── depd@1.1.2
│ ├─┬ http-errors@1.6.2
│ │ ├── depd@1.1.1
│ │ ├── inherits@2.0.3
│ │ ├── setprototypeof@1.0.3
│ │ └── statuses@1.4.0
│ ├── iconv-lite@0.4.19
│ ├─┬ on-finished@2.3.0
│ │ └── ee-first@1.1.1
│ ├── qs@6.5.1
│ ├─┬ raw-body@2.3.2
│ │ └── unpipe@1.0.0
│ └─┬ type-is@1.6.15
│   ├── media-typer@0.3.0
│   └─┬ mime-types@2.1.17
│     └── mime-db@1.30.0
├── date-format-lite@17.7.0
├── ejs@2.5.7
├─┬ elasticsearch@13.3.1
│ ├── agentkeepalive@2.2.0
│ ├─┬ chalk@1.1.3
│ │ ├── ansi-styles@2.2.1
│ │ ├── escape-string-regexp@1.0.5
│ │ ├─┬ has-ansi@2.0.0
│ │ │ └── ansi-regex@2.1.1
│ │ ├─┬ strip-ansi@3.0.1
│ │ │ └── ansi-regex@2.1.1
│ │ └── supports-color@2.0.0
│ ├── lodash@2.4.2
│ ├── lodash.get@4.4.2
│ ├── lodash.isempty@4.4.0
│ └── lodash.trimend@4.5.1
├─┬ eslint@4.15.0
│ ├─┬ babel-code-frame@6.26.0
│ │ ├─┬ chalk@1.1.3
│ │ │ ├── ansi-styles@2.2.1
│ │ │ ├── escape-string-regexp@1.0.5
│ │ │ ├─┬ has-ansi@2.0.0
│ │ │ │ └── ansi-regex@2.1.1
│ │ │ ├─┬ strip-ansi@3.0.1
│ │ │ │ └── ansi-regex@2.1.1
│ │ │ └── supports-color@2.0.0
│ │ └── js-tokens@3.0.2
│ ├─┬ chalk@2.3.0
│ │ ├─┬ ansi-styles@3.2.0
│ │ │ └─┬ color-convert@1.9.1
│ │ │   └── color-name@1.1.3
│ │ ├── escape-string-regexp@1.0.5
│ │ └─┬ supports-color@4.5.0
│ │   └── has-flag@2.0.0
│ ├─┬ concat-stream@1.6.0
│ │ ├── inherits@2.0.3
│ │ ├─┬ readable-stream@2.3.3
│ │ │ ├── core-util-is@1.0.2
│ │ │ ├── isarray@1.0.0
│ │ │ ├── process-nextick-args@1.0.7
│ │ │ ├── safe-buffer@5.1.1
│ │ │ ├── string_decoder@1.0.3
│ │ │ └── util-deprecate@1.0.2
│ │ └── typedarray@0.0.6
│ ├─┬ cross-spawn@5.1.0
│ │ ├─┬ shebang-command@1.2.0
│ │ │ └── shebang-regex@1.0.0
│ │ └─┬ which@1.3.0
│ │   └── isexe@2.0.0
│ ├─┬ debug@3.1.0
│ │ └── ms@2.0.0
│ ├── doctrine@2.1.0
│ ├─┬ eslint-scope@3.7.1
│ │ ├─┬ esrecurse@4.2.0
│ │ │ └── object-assign@4.1.1
│ │ └── estraverse@4.2.0
│ ├── eslint-visitor-keys@1.0.0
│ ├─┬ espree@3.5.2
│ │ ├── acorn@5.3.0
│ │ └─┬ acorn-jsx@3.0.1
│ │   └── acorn@3.3.0
│ ├─┬ esquery@1.0.0
│ │ └── estraverse@4.2.0
│ ├── esutils@2.0.2
│ ├─┬ file-entry-cache@2.0.0
│ │ ├─┬ flat-cache@1.3.0
│ │ │ ├── circular-json@0.3.3
│ │ │ ├─┬ del@2.2.2
│ │ │ │ ├─┬ globby@5.0.0
│ │ │ │ │ ├─┬ array-union@1.0.2
│ │ │ │ │ │ └── array-uniq@1.0.3
│ │ │ │ │ └── arrify@1.0.1
│ │ │ │ ├── is-path-cwd@1.0.0
│ │ │ │ ├─┬ is-path-in-cwd@1.0.0
│ │ │ │ │ └── is-path-inside@1.0.1
│ │ │ │ ├── pify@2.3.0
│ │ │ │ ├─┬ pinkie-promise@2.0.1
│ │ │ │ │ └── pinkie@2.0.4
│ │ │ │ └── rimraf@2.6.2
│ │ │ ├── graceful-fs@4.1.11
│ │ │ └── write@0.2.1
│ │ └── object-assign@4.1.1
│ ├── functional-red-black-tree@1.0.1
│ ├─┬ glob@7.1.2
│ │ ├── fs.realpath@1.0.0
│ │ ├─┬ inflight@1.0.6
│ │ │ └── wrappy@1.0.2
│ │ ├── inherits@2.0.3
│ │ ├─┬ once@1.4.0
│ │ │ └── wrappy@1.0.2
│ │ └── path-is-absolute@1.0.1
│ ├── globals@11.1.0
│ ├── ignore@3.3.7
│ ├── imurmurhash@0.1.4
│ ├─┬ inquirer@3.3.0
│ │ ├── ansi-escapes@3.0.0
│ │ ├─┬ cli-cursor@2.1.0
│ │ │ └─┬ restore-cursor@2.0.0
│ │ │   ├─┬ onetime@2.0.1
│ │ │   │ └── mimic-fn@1.1.0
│ │ │   └── signal-exit@3.0.2
│ │ ├── cli-width@2.2.0
│ │ ├─┬ external-editor@2.1.0
│ │ │ ├── chardet@0.4.2
│ │ │ ├── iconv-lite@0.4.19
│ │ │ └─┬ tmp@0.0.33
│ │ │   └── os-tmpdir@1.0.2
│ │ ├─┬ figures@2.0.0
│ │ │ └── escape-string-regexp@1.0.5
│ │ ├── mute-stream@0.0.7
│ │ ├─┬ run-async@2.3.0
│ │ │ └── is-promise@2.1.0
│ │ ├── rx-lite@4.0.8
│ │ ├── rx-lite-aggregates@4.0.8
│ │ ├─┬ string-width@2.1.1
│ │ │ └── is-fullwidth-code-point@2.0.0
│ │ └── through@2.3.8
│ ├── is-resolvable@1.0.1
│ ├─┬ js-yaml@3.10.0
│ │ ├─┬ argparse@1.0.9
│ │ │ └── sprintf-js@1.0.3
│ │ └── esprima@4.0.0
│ ├── json-stable-stringify-without-jsonify@1.0.1
│ ├─┬ levn@0.3.0
│ │ ├── prelude-ls@1.1.2
│ │ └── type-check@0.3.2
│ ├── lodash@4.17.4
│ ├─┬ minimatch@3.0.4
│ │ └─┬ brace-expansion@1.1.8
│ │   ├── balanced-match@1.0.0
│ │   └── concat-map@0.0.1
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ ├── natural-compare@1.4.0
│ ├─┬ optionator@0.8.2
│ │ ├── deep-is@0.1.3
│ │ ├── fast-levenshtein@2.0.6
│ │ ├── prelude-ls@1.1.2
│ │ ├── type-check@0.3.2
│ │ └── wordwrap@1.0.0
│ ├── path-is-inside@1.0.2
│ ├── pluralize@7.0.0
│ ├── progress@2.0.0
│ ├─┬ require-uncached@1.0.3
│ │ ├─┬ caller-path@0.1.0
│ │ │ └── callsites@0.2.0
│ │ └── resolve-from@1.0.1
│ ├── semver@5.5.0
│ ├─┬ strip-ansi@4.0.0
│ │ └── ansi-regex@3.0.0
│ ├── strip-json-comments@2.0.1
│ ├─┬ table@4.0.2
│ │ ├── ajv-keywords@2.1.1
│ │ ├─┬ slice-ansi@1.0.0
│ │ │ └── is-fullwidth-code-point@2.0.0
│ │ └─┬ string-width@2.1.1
│ │   └── is-fullwidth-code-point@2.0.0
│ └── text-table@0.2.0
├─┬ eslint-config-prettier@2.9.0
│ └── get-stdin@5.0.1
├─┬ eslint-plugin-node@5.2.1
│ ├── ignore@3.3.7
│ ├─┬ minimatch@3.0.4
│ │ └─┬ brace-expansion@1.1.8
│ │   ├── balanced-match@1.0.0
│ │   └── concat-map@0.0.1
│ ├─┬ resolve@1.5.0
│ │ └── path-parse@1.0.5
│ └── semver@5.3.0
├─┬ eslint-plugin-prettier@2.5.0
│ ├── fast-diff@1.1.2
│ └── jest-docblock@21.2.0
├─┬ express@4.16.2
│ ├─┬ accepts@1.3.4
│ │ ├─┬ mime-types@2.1.17
│ │ │ └── mime-db@1.30.0
│ │ └── negotiator@0.6.1
│ ├── array-flatten@1.1.1
│ ├── content-disposition@0.5.2
│ ├── content-type@1.0.4
│ ├── cookie@0.3.1
│ ├── cookie-signature@1.0.6
│ ├─┬ debug@2.6.9
│ │ └── ms@2.0.0
│ ├── depd@1.1.2
│ ├── encodeurl@1.0.1
│ ├── escape-html@1.0.3
│ ├── etag@1.8.1
│ ├─┬ finalhandler@1.1.0
│ │ └── unpipe@1.0.0
│ ├── fresh@0.5.2
│ ├── merge-descriptors@1.0.1
│ ├── methods@1.1.2
│ ├─┬ on-finished@2.3.0
│ │ └── ee-first@1.1.1
│ ├── parseurl@1.3.2
│ ├── path-to-regexp@0.1.7
│ ├── qs@6.5.1
│ ├── range-parser@1.2.0
│ ├── safe-buffer@5.1.1
│ ├─┬ send@0.16.1
│ │ ├── destroy@1.0.4
│ │ ├─┬ http-errors@1.6.2
│ │ │ ├── depd@1.1.1
│ │ │ ├── inherits@2.0.3
│ │ │ └── setprototypeof@1.0.3
│ │ ├── mime@1.4.1
│ │ └── ms@2.0.0
│ ├── serve-static@1.13.1
│ ├── setprototypeof@1.1.0
│ ├── statuses@1.3.1
│ ├─┬ type-is@1.6.15
│ │ ├── media-typer@0.3.0
│ │ └─┬ mime-types@2.1.17
│ │   └── mime-db@1.30.0
│ ├── utils-merge@1.0.1
│ └── vary@1.1.2
├─┬ express-ws@3.0.0
│ └─┬ ws@2.3.1
│   ├── safe-buffer@5.0.1
│   └── ultron@1.1.1
├── immutable@4.0.0-rc.9
├─┬ lru-cache@4.1.1
│ ├── pseudomap@1.0.2
│ └── yallist@2.1.2
├─┬ md5@2.2.1
│ ├── charenc@0.0.2
│ ├── crypt@0.0.2
│ └── is-buffer@1.1.6
├── micro-strptime@0.2.2
├─┬ mocha@4.1.0
│ ├── browser-stdout@1.3.0
│ ├── commander@2.11.0
│ ├─┬ debug@3.1.0
│ │ └── ms@2.0.0
│ ├── diff@3.3.1
│ ├── escape-string-regexp@1.0.5
│ ├─┬ glob@7.1.2
│ │ ├── fs.realpath@1.0.0
│ │ ├─┬ inflight@1.0.6
│ │ │ └── wrappy@1.0.2
│ │ ├── inherits@2.0.3
│ │ ├─┬ minimatch@3.0.4
│ │ │ └─┬ brace-expansion@1.1.8
│ │ │   ├── balanced-match@1.0.0
│ │ │   └── concat-map@0.0.1
│ │ ├─┬ once@1.4.0
│ │ │ └── wrappy@1.0.2
│ │ └── path-is-absolute@1.0.1
│ ├── growl@1.10.3
│ ├── he@1.1.1
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8
│ └─┬ supports-color@4.4.0
│   └── has-flag@2.0.0
├── prettier@1.10.2
├─┬ proxy-addr@2.0.2
│ ├── forwarded@0.1.2
│ └── ipaddr.js@1.5.2
├─┬ rc@1.2.4
│ ├── deep-extend@0.4.2
│ ├── ini@1.3.5
│ ├── minimist@1.2.0
│ └── strip-json-comments@2.0.1
├── syslog-parse@1.3.1
├── tail@1.2.3
├─┬ url@0.11.0
│ ├── punycode@1.3.2
│ └── querystring@0.2.0
├── uuid@3.2.1
└─┬ ws@3.3.3
  ├── async-limiter@1.0.0
  ├── safe-buffer@5.1.1
  └── ultron@1.1.1
```

**Comment by znarf** [comment]
Thank you very much for reporting the issue. We actually just broke master a few hours ago.

It's fixed in: https://github.com/access-watch/access-watch/commit/d5ab9325a1df26b7cdb17e208bd0c4de58ce4f08
