### ISSUE TITLE
Issues running latest master on Alpine Linux

### ISSUE THREAD

**Issue by realies** [access-watch/access-watch#129]
Just noticed that the compiling latest master on alpine linux within in a container is broken. [Here](https://github.com/realies/access-watch-docker/blob/3fe59dbe1d517a73e96f26b7e61c307cb36608ba/Dockerfile) is the recipe for the image. Upon starting the container:

```
> access-watch@0.8.0 start /access-watch
> node start "config/custom"

module.js:538
    throw err;
    ^

Error: Cannot find module '../lib/pipeline'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/access-watch/config/custom.js:1:80)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! access-watch@0.8.0 start: `node start "config/custom"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the access-watch@0.8.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-01-21T04_04_50_096Z-debug.log
```

with the log file containing:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start', 'config/custom' ]
2 info using npm@5.5.1
3 info using node@v8.9.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle access-watch@0.8.0~prestart: access-watch@0.8.0
6 info lifecycle access-watch@0.8.0~start: access-watch@0.8.0
7 verbose lifecycle access-watch@0.8.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle access-watch@0.8.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/access-watch/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle access-watch@0.8.0~start: CWD: /access-watch
10 silly lifecycle access-watch@0.8.0~start: Args: [ '-c', 'node start "config/custom"' ]
11 silly lifecycle access-watch@0.8.0~start: Returned: code: 1  signal: null
12 info lifecycle access-watch@0.8.0~start: Failed to exec start script
13 verbose stack Error: access-watch@0.8.0 start: `node start "config/custom"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid access-watch@0.8.0
15 verbose cwd /access-watch
16 verbose Linux 4.14.12-unRAID
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start" "config/custom"
18 verbose node v8.9.3
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error access-watch@0.8.0 start: `node start "config/custom"`
22 error Exit status 1
23 error Failed at the access-watch@0.8.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Ideas what could have gone wrong?

**Comment by znarf** [comment]
@realies Sorry, there is a breaking change in the configuration file.

What was before:

```
const pipeline = require('../lib/pipeline');
const input = require('../input');
const format = require('../format');
```

Should be now written:

```
const accessWatch = require('../access-watch')();
const { pipeline, input, format } = accessWatch;
```

**Comment by realies** [comment]
Thanks for clarifying. Would be great to be possible for Access Watch to let users with old configs know of this.

**Comment by znarf** [comment]
@realies absolutely right, on which channel would you expect us to communicate?

One part of the problem is that we're encouraging to use master right now, as soon as we reach a version we're confortable with, we'll use releases instead.

**Comment by realies** [comment]
@znarf, would expect to see this in the software output/log. Might be too early for this, but it would be reasonable to implement breaking change log notifications in future releases.
