### ISSUE TITLE
TypeError: Object.values is not a function

### ISSUE THREAD

**Issue by Dark-Vex** [access-watch/access-watch#150]
### Linux version
```
root@8a8c159a3596:/# cat /etc/debian_version
9.3
```

When try to start access-watch with npm start I receive the following error
```
root@8a8c159a3596:/access-watch# npm start
> access-watch@0.8.3 start /access-watch
> node start

/access-watch/src/plugins/proxy.js:80
  ...Object.values(ipRanges)
            ^

TypeError: Object.values is not a function
    at Object.<anonymous> (/access-watch/src/plugins/proxy.js:80:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/access-watch/src/pipeline/augmented.js:6:15)
    at Module._compile (module.js:570:32)

npm ERR! Linux 4.9.0-5-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.12.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! access-watch@0.8.3 start: `node start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the access-watch@0.8.3 start script 'node start'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the access-watch package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node start
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs access-watch
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls access-watch
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /access-watch/npm-debug.log
```

### Attached here /access-watch/npm-debug.log
```
root@8a8c159a3596:/# cat /access-watch/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.10
3 info using node@v6.12.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle access-watch@0.8.3~prestart: access-watch@0.8.3
6 silly lifecycle access-watch@0.8.3~prestart: no script for prestart, continuing
7 info lifecycle access-watch@0.8.3~start: access-watch@0.8.3
8 verbose lifecycle access-watch@0.8.3~start: unsafe-perm in lifecycle true
9 verbose lifecycle access-watch@0.8.3~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/access-watch/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle access-watch@0.8.3~start: CWD: /access-watch
11 silly lifecycle access-watch@0.8.3~start: Args: [ '-c', 'node start' ]
12 silly lifecycle access-watch@0.8.3~start: Returned: code: 1  signal: null
13 info lifecycle access-watch@0.8.3~start: Failed to exec start script
14 verbose stack Error: access-watch@0.8.3 start: `node start`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:920:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
15 verbose pkgid access-watch@0.8.3
16 verbose cwd /access-watch
17 error Linux 4.9.0-5-amd64
18 error argv "/usr/bin/node" "/usr/bin/npm" "start"
19 error node v6.12.3
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error access-watch@0.8.3 start: `node start`
22 error Exit status 1
23 error Failed at the access-watch@0.8.3 start script 'node start'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the access-watch package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node start
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs access-watch
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls access-watch
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by znarf** [comment]
Thank your for your report @Dark-Vex, we only support node >= 7 at the moment. We try to properly disclose that wherever it makes sense, but let us know if you see somewhere else where that should be mentioned.

Fore node 6, you might try to use the `harmony flag`, as explained in this forum discussion:
https://discuss.access.watch/d/56-not-running-with-node-6

Last time we checked, this was working.

**Comment by Dark-Vex** [comment]
@znarf ok thanks! I will try and I let you know. Sorry, yesterday I didn't noticed/checked the minimum requirements of nodejs 7, my fault!
