### ISSUE TITLE
Unhandled Exception: ECONNRESET

### ISSUE THREAD

**Issue by znarf** [access-watch/access-watch#162]
```
Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:615:25)
```

```
 App [access-watch] with id [0] and pid [16059], exited with code [1] via signal [SIGINT]
```

**Comment by znarf** [comment]
Happened again.

```2018-02-21 02:38:41: App [access-watch] with id [0] and pid [20093], exited with code [1] via signal [SIGINT]```

```2018-02-21T02:38:41+00:00: Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:615:25)```

**Comment by znarf** [comment]
Pushed a fix to handle errors on TCP socket input.
https://github.com/access-watch/access-watch/commit/f2f921f9abb7bf17dd4388a8f583e338e5512610

But it's not sure if that error is triggered from here. That could also possibly be a Websocket issue.

**Comment by znarf** [comment]
Got this one today:

```
2018-02-28 13:55:49: App [access-watch] with id [0] and pid [20707], exited with code [1] via signal [SIGINT]
```

```
2018-02-28T13:55:49+00:00: Error: write EPIPE
    at _errnoException (util.js:1022:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:867:14)
```
