### ISSUE TITLE
ajv-keywords requires a peer of ajv@^5.0.0

### ISSUE THREAD

**Issue by znarf** [access-watch/access-watch#176]
When doing `npm install`

`npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.`

Which package is requiring  `ajv-keywords` ?

**Comment by znarf** [comment]
Answer!

`eslint` (4.18.1) is requiring `table` (4.0.2) which is requiring `ajv` (5.5.2) and `ajv-keywords` (2.1.1)

because we now have `ajv` 6.1.1, the `ajv` 5.5.2 required for `table` is installed in `table` node_modules, but `ajv-keywords` is installed in main node_modules

Looking at `table` dependencies (on master, not released), I see:

```
    "ajv": "^6.0.1",
    "ajv-keywords": "^3.0.0",
```

So, `ajv-keywords` 3.1.0, will upgrade its `ajv` peer dependency to

```
 "ajv": "^6.0.0"
```

So, the problem should be fixed in next iteration of `table`, and if/when `eslint` will update its own dependencies of `table` and `ajv`.

**Comment by znarf** [comment]
I'm  not sure what is currently broken with the current situation.

**Comment by realies** [comment]
Noticed the Access Watch Docker container I'm maintaining is also broken.

```
> access-watch@0.10.1 start /access-watch
> node start "/config.js"

Loaded /access-watch/data/metrics.json in 0.001s
Loaded /access-watch/data/session.json in 0s
Loaded /access-watch/data/rules.json in 0s
/access-watch/node_modules/ajv/lib/ajv.js:92
if (!v) throw new Error('no schema with key or ref "' + schemaKeyRef + '"');
^

Error: no schema with key or ref "http://json-schema.org/draft-06/schema#"
at Ajv.validate (/access-watch/node_modules/ajv/lib/ajv.js:92:19)
at Ajv.validateSchema (/access-watch/node_modules/ajv/lib/ajv.js:178:22)
at Ajv._addSchema (/access-watch/node_modules/ajv/lib/ajv.js:312:10)
at Ajv.compile (/access-watch/node_modules/ajv/lib/ajv.js:112:24)
at Object.<anonymous> (/access-watch/src/lib/pipeline.js:21:28)
at Module._compile (module.js:635:30)
at Object.Module._extensions..js (module.js:646:10)
at Module.load (module.js:554:32)
at tryModuleLoad (module.js:497:12)
at Function.Module._load (module.js:489:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! access-watch@0.10.1 start: `node start "/config.js"`
npm ERR! Exit status 1


npm ERR! Failed at the access-watch@0.10.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2018-02-23T03_16_18_883Z-debug.log
```

2018-02-23T03_16_18_883Z-debug.log
```
0 info it worked if it ends with ok                                                                                     
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start', '/config.js' ]                                                
2 info using npm@5.5.1                                                                                                  
3 info using node@v8.9.3                                                                                                
4 verbose run-script [ 'prestart', 'start', 'poststart' ]                                                               
5 info lifecycle access-watch@0.10.1~prestart: access-watch@0.10.1                                                      
6 info lifecycle access-watch@0.10.1~start: access-watch@0.10.1                                                         
7 verbose lifecycle access-watch@0.10.1~start: unsafe-perm in lifecycle true                                            
8 verbose lifecycle access-watch@0.10.1~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/access-watch/node_modul
es/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin                                                    
9 verbose lifecycle access-watch@0.10.1~start: CWD: /access-watch                                                       
10 silly lifecycle access-watch@0.10.1~start: Args: [ '-c', 'node start "/config.js"' ]                                 
11 silly lifecycle access-watch@0.10.1~start: Returned: code: 1  signal: null                                           
12 info lifecycle access-watch@0.10.1~start: Failed to exec start script                                                
13 verbose stack Error: access-watch@0.10.1 start: `node start "/config.js"`                                            
13 verbose stack Exit status 1                                                                                          
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16) 
13 verbose stack     at emitTwo (events.js:126:13)                                                                      
13 verbose stack     at EventEmitter.emit (events.js:214:7)                                                             
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:1
4)                                                                                                                      
13 verbose stack     at emitTwo (events.js:126:13)                                                                      
13 verbose stack     at ChildProcess.emit (events.js:214:7)                                                             
13 verbose stack     at maybeClose (internal/child_process.js:925:16)                                                   
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)                           
14 verbose pkgid access-watch@0.10.1                                                                                    
15 verbose cwd /access-watch                                                                                            
16 verbose Linux 4.14.16                                                                                         
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start" "/config.js"                                                     
18 verbose node v8.9.3                                                                                                  
19 verbose npm  v5.5.1                                                                                                  
20 error code ELIFECYCLE                                                                                                
21 error errno 1                                                                                                        
22 error access-watch@0.10.1 start: `node start "/config.js"`                                                           
22 error Exit status 1                                                                                                  
23 error Failed at the access-watch@0.10.1 start script.                                                                
23 error This is probably not a problem with npm. There is likely additional logging output above.                      
24 verbose exit [ 1, true ]  
```

**Comment by znarf** [comment]
hi @realies, the latest version 0.11.0, should be stable and not have this error.

**Comment by realies** [comment]
@znarf, `bab34ef` fixes it. Perhaps I should maintain a `stable` and `latest` tags for the container.

**Comment by znarf** [comment]
Normally, `master` should now be stable, the `dev' branch being the latest.

**Comment by znarf** [comment]
Warning is gone.

**Comment by znarf** [comment]
Not.

**Comment by debragail** [comment]
I'm getting this when trying to npm install jest and i've already installed ajv manually and it still throws

`npm install --save-dev jest
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
 jest@23.6.0
updated 1 package in 39.572s`

**Comment by skartknet** [comment]
same issue trying to install @riophae/vue-treeselect
