### ISSUE TITLE
Error when clicking on address

### ISSUE THREAD

**Issue by benfle** [access-watch/access-watch#86]
I'm getting this error when the dashboard tries to display the request stream of an address or a robot.

This only happens when there is a blocking rule in the database. So this might be a problem on the server side but I can't figure out how the websocket log stream and the rules are connected.

Hopefully @jduthon can explain the source of the error on the client side and that might help me find to the problem on the server side.
 
```
main.js:1 TypeError: Cannot read property 'length' of undefined
    at http://localhost:3000/dashboard/main.js:1:70496
    at Array.find (native)
    at t.project (http://localhost:3000/dashboard/main.js:1:70451)
    at t._next (http://localhost:3000/dashboard/main.js:1:922139)
    at t.next (http://localhost:3000/dashboard/main.js:1:10597)
    at t.next (http://localhost:3000/dashboard/main.js:1:31122)
    at t.next (http://localhost:3000/dashboard/main.js:1:218398)
    at t._next (http://localhost:3000/dashboard/main.js:1:10926)
    at t.next (http://localhost:3000/dashboard/main.js:1:10597)
    at t._tryNext (http://localhost:3000/dashboard/main.js:1:931601)
```

**Comment by jduthon** [comment]
I believe you are not using `conditions` anymore right?
Right now I was matching the fact that there is a `conditions` property per rule, and that it is a map containing many `condition`.
Tell me when it is ready on your side and close to be merged and I will adapt the front :)
(Or I can make a front branch matching yours if necessary)

**Comment by benfle** [comment]
@jduthon Alright, thanks. I will let you know when the branch is ready with the new model.
